// Create web server
// Start server
// Create route to handle comments
// Create route to handle comment form submission
// Create route to handle comment deletion
// Create route to handle comment editing
// Create route to handle comment updating
// Create route to handle comment upvoting
// Create route to handle comment downvoting
// Create route to handle comment flagging
// Create route to handle comment unflagging
// Create route to handle comment reporting
// Create route to handle comment unreporting
// Create route to handle comment banning
// Create route to handle comment unbanning
// Create route to handle comment approval
// Create route to handle comment unapproval
// Create route to handle comment listing
// Create route to handle comment viewing
// Create route to handle comment searching
// Create route to handle comment sorting
// Create route to handle comment pagination
// Create route to handle comment counting
// Create route to handle comment resetting
// Create route to handle comment exporting
// Create route to handle comment importing
// Create route to handle comment purging
// Create route to handle comment archiving
// Create route to handle comment unarchiving
// Create route to handle comment locking
// Create route to handle comment unlocking
// Create route to handle comment subscribing
// Create route to handle comment unsubscribing
// Create route to handle comment liking
// Create route to handle comment unliking
// Create route to handle comment sharing
// Create route to handle comment unsharing
// Create route to handle comment copying
// Create route to handle comment moving
// Create route to handle comment merging
// Create route to handle comment splitting
// Create route to handle comment tagging
// Create route to handle comment untagging
// Create route to handle comment categorizing
// Create route to handle comment uncategorizing
// Create route to handle comment rating
// Create route to handle comment flagging
// Create route to handle comment unflagging
// Create route to handle comment reporting
// Create route to handle comment unreporting
// Create route to handle comment banning
// Create route to handle comment unbanning
// Create route to handle comment approval
// Create route to handle comment unapproval
// Create route to handle comment listing
// Create route to handle comment viewing
// Create route to handle comment searching
// Create route to handle comment sorting
// Create route to handle comment pagination
// Create route to handle comment counting